### ISSUE TITLE
Problem with go build on Ubuntu 20.04 and Ubuntu 18.04

### ISSUE THREAD

**Issue by cyb3r5t4lk3r** [mdsecactivebreach/o365-attack-toolkit#21]
Hello 

I have a problem with deployment. I have a Ubuntu Desktop 20.04 LTS (same issue on Ubuntu Server 18.04 LTS without GUI) and I can not build a new version of O365-Attack-Toolkit.

**go ver** -> go version go1.12.2 gccgo (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0 linux/amd64
**uname -a** -> Linux UClient 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
**libc** --> GNU C Library (Ubuntu GLIBC 2.31-0ubuntu9.1) stable release version 2.31.

My go Variables and path
GOPATH="/home/adminlab/go"
GOROOT="/usr"

Root O365 Attack Toolkit is here /home/adminlab/go/src/o365-attack-toolkit

The system returns this error after "go build". I have the same error if I use the user or root. Error is below. 

adminlab@UClient: ~/go/src/o365-attack-toolkit$ go build
o365-attack-toolkit
/bin/ld: $WORK/b001/_pkg1_.a(_x011.o): undefined reference to symbol 'pthread_mutex_trylock@@GLIBC_2.2.5'
/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

![image](https://user-images.githubusercontent.com/29402116/98425780-c0659c80-2096-11eb-80c4-ef0f3bb9fa1c.png)
